(()=>{let e="https://api.open-meteo.com/v1/forecast?latitude=50.7024211&longitude=15.4171592&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_sum,wind_speed_10m_max&timezone=Europe/Prague&forecast_days=7",v={cs:"cs-CZ",en:"en-GB",de:"de-DE"},f={0:{icon:"☀️",message:"clear"},1:{icon:"🌤️",message:"mainlyClear"},2:{icon:"⛅",message:"partlyCloudy"},3:{icon:"☁️",message:"overcast"},45:{icon:"🌫️",message:"fog"},48:{icon:"🌫️",message:"rime"},51:{icon:"🌧️",message:"drizzle"},53:{icon:"🌧️",message:"drizzle"},55:{icon:"🌧️",message:"drizzle"},56:{icon:"🌧️",message:"freezingDrizzle"},57:{icon:"🌧️",message:"freezingDrizzle"},61:{icon:"🌧️",message:"lightRain"},63:{icon:"🌧️",message:"rain"},65:{icon:"🌧️",message:"heavyRain"},66:{icon:"🌧️",message:"freezingRain"},67:{icon:"🌧️",message:"freezingRain"},71:{icon:"🌨️",message:"lightSnow"},73:{icon:"🌨️",message:"snow"},75:{icon:"🌨️",message:"heavySnow"},77:{icon:"🌨️",message:"snowGrains"},80:{icon:"🌦️",message:"showers"},81:{icon:"🌦️",message:"showers"},82:{icon:"🌦️",message:"heavyShowers"},85:{icon:"🌨️",message:"snowShowers"},86:{icon:"🌨️",message:"snowShowers"},95:{icon:"⛈️",message:"thunderstorm"},96:{icon:"⛈️",message:"hailThunderstorm"},99:{icon:"⛈️",message:"hailThunderstorm"}},y=["today","unknown","loadError",...new Set(Object.values(f).map(e=>e.message))];function s(){fetch(e).then(e=>{if(e.ok)return e.json();throw new Error("Weather request failed with status "+e.status)}).then(e=>{var m=document.getElementById("weather-forecast");if(m){let a,s,t,{locale:n,messages:i}=(a=>{var e=(a.dataset.language||document.documentElement.lang||"cs").toLowerCase().split("-")[0],s=y.filter(e=>!a.dataset[e]);if(0<s.length)throw new Error("Missing weather translations: "+s.join(", "));return{locale:v[e]||v.cs,messages:a.dataset}})(m),r=e.daily,o='<div class="weather-days">';for(let e=0;e<r.time.length;e++){var{dayName:c,dateStr:d}=((e,a)=>{var[e,s,t]=e.split("-").map(Number),e=new Date(Date.UTC(e,s-1,t)),s=new Intl.DateTimeFormat(a,{weekday:"short",timeZone:"UTC"}).format(e);return{dayName:s.charAt(0).toLocaleUpperCase(a)+s.slice(1),dateStr:new Intl.DateTimeFormat(a,{day:"numeric",month:"short",timeZone:"UTC"}).format(e)}})(r.time[e],n),l=(a=r.weather_code[e],s=i,t=void 0,(t=f[a])?{icon:t.icon,desc:s[t.message]}:{icon:"❓",desc:s.unknown}),h=Math.round(r.temperature_2m_max[e]),g=Math.round(r.temperature_2m_min[e]),w=r.precipitation_sum[e],u=Math.round(r.wind_speed_10m_max[e]),p=0===e;o+=`
                <div class="weather-day${p?" weather-today":""}">
                    <div class="weather-day-name">${p?i.today:c}</div>
                    <div class="weather-day-date">${d}</div>
                    <div class="weather-icon">${l.icon}</div>
                    <div class="weather-desc">${l.desc}</div>
                    <div class="weather-temps">
                        <span class="temp-max"><small>max</small> ${h}°</span>
                        <span class="temp-min"><small>min</small> ${g}°</span>
                    </div>
                    <div class="weather-details">
                        <span class="weather-wind"><i class="fa fa-flag"></i> ${u} km/h</span>
                        ${0<w?`<span class="weather-precip"><i class="fa fa-tint"></i> ${w.toFixed(1)} mm</span>`:""}
                    </div>
                </div>
            `}o+="</div>",m.innerHTML=o}}).catch(e=>{var a,s=document.getElementById("weather-forecast");s&&((a=document.createElement("div")).className="weather-error",a.textContent=s.dataset.loadError,s.replaceChildren(a))})}function a(){var e=document.querySelector(".weather");if(e)if("IntersectionObserver"in window){let a=new IntersectionObserver(e=>{e.forEach(e=>{e.isIntersecting&&(s(),a.disconnect())})},{rootMargin:"100px"});a.observe(e)}else s()}"complete"===document.readyState?setTimeout(a,100):window.addEventListener("load",()=>setTimeout(a,100))})();